Pages/Categories/Add.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Utils;

namespace EventScoringWeb.Pages.Categories
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class AddModel : PageModel
    {
        private readonly ICategoryRepository _categories;
        private readonly IEventRepository _events;

        public AddModel(ICategoryRepository categories, IEventRepository events)
        {
            _categories = categories;
            _events = events;
        }

        [BindProperty]
        public Category Category { get; set; }

        public IActionResult OnGet(Guid eventId)
        {
            Category = new Category();
            Category.EventId = eventId;

            // authorize if logged in user is the owner of the event.
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var evenT = _events.GetFirstOrDefault(u => u.EventId.Equals(eventId), p => p.ApplicationUser);
            if (evenT == null || evenT.ApplicationUserId != userId)
            {
                return RedirectToPage("Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _categories.Add(Category);
            _categories.Save();

            return RedirectToPage(nameof(Index), new { eventid = Category.EventId });
        }
    }
}

Pages/Categories/Edit.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Utils;

namespace EventScoringWeb.Pages.Categories
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class EditModel : PageModel
    {

        private readonly ICategoryRepository _categories;

        public EditModel(ICategoryRepository categories)
        {
            _categories = categories;
        }

        [BindProperty]
        public Category Category { get; set; }
        // for dashboard
        public Guid EventId { get; set; }

        public IActionResult OnGet(Guid id)
        {
            Category = _categories.GetFirstOrDefault(
                p => p.CategoryId.Equals(id),
                includes: p => p.Event);

            if (Category == null)
            {
               // maybe redirect to error page (?)
                return RedirectToPage("Index");
            }

            EventId = (Guid)Category.EventId;
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                // Maybe give more error information
                return Page();
            }

            _categories.Update(Category);
            return RedirectToPage("Index", new { eventid = Category.EventId });
        }
    }
}

Pages/Competitions/Add.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Utils;

namespace EventScoringWeb.Pages.Competitions
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class AddModel : PageModel
    {
        private readonly ICompetitionRepository _competitions;
        private readonly ICategoryRepository _categories;

        public AddModel(ICompetitionRepository competitions, ICategoryRepository categories)
        {
            _competitions = competitions;
            _categories = categories;
        }

        [BindProperty]
        public Competition Competition { get; set; }
        //[BindProperty]
        public SelectList Categories { get; set; }

        public void OnGet(Guid eventId)
        {
            Competition = new Competition();
            Competition.EventId = eventId;

            Categories = new SelectList(
                _categories
                    .GetAll(filter: p => p.EventId.Equals(eventId), includes: p => p.Event)
                    .Select(i => new
                    {
                        Text = i.Name,
                        Value = i.CategoryId
                    }).ToList(), "Value", "Text");

        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                PopulateCategoriesList(Competition.EventId);
                return Page();
            }
            if (Competition.CategoryId == null)
            {
                PopulateCategoriesList(Competition.EventId);
                ModelState.AddModelError("no-selected-category", "Please select a category");
                return Page();
            }

            _competitions.Add(Competition);
            _competitions.Save();

            return RedirectToPage("Index", new { eventId = Competition.EventId });
        }

        public void PopulateCategoriesList(Guid? eventId)
        {
            Categories = new SelectList(
            _categories
                .GetAll(filter: p => p.EventId.Equals(eventId), includes: p => p.Event)
                .Select(i => new
                {
                    Text = i.Name,
                    Value = i.CategoryId
                }).ToList(), "Value", "Text");
        }
    }
}

Pages/Competitions/Edit.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Utils;

namespace EventScoringWeb.Pages.Competitions
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class EditModel : PageModel
    {
        private readonly ICompetitionRepository _competitions;
        private readonly ICategoryRepository _categories;

        public EditModel(ICompetitionRepository competitions, ICategoryRepository categories)
        {
            _competitions = competitions;
            _categories = categories;
        }

        [BindProperty]
        public Competition Competition { get; set; }
        //[BindProperty]
        public SelectList Categories { get; set; }

        public void OnGet(Guid id)
        {
            Competition = _competitions.GetFirstOrDefault(
                filter: p => p.CompetitionId.Equals(id),
                p => p.Event,
                p => p.Category
            );

            Categories = new SelectList(
            _categories
                .GetAll(filter: p => p.EventId.Equals(Competition.EventId), includes: p => p.Event)
                .Select(i => new
                {
                    Text = i.Name,
                    Value = i.CategoryId,
                }).ToList(), "Value", "Text", Competition.CategoryId);
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Categories = new SelectList(
                    _categories
                        .GetAll(filter: p => p.EventId.Equals(Competition.EventId), includes: p => p.Event)
                        .Select(i => new
                        {
                            Text = i.Name,
                            Value = i.CategoryId,
                        }).ToList(), "Value", "Text", Competition.CategoryId);
                return Page();
            }

            _competitions.Update(Competition);

            return RedirectToPage("Index", new { eventId = Competition.EventId });
        }
    }
}

Pages/Contestants/Add.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using Utils;

namespace EventScoringWeb.Pages.Contestants
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class AddModel : PageModel
    {
        private readonly IEventRepository _events;
        private readonly IContestantRepository _contestants;
        private readonly ITeamRepository _teams;
        private readonly ICompetitionRepository _competitions;

        public AddModel(
            IEventRepository events,
            IContestantRepository contestants,
            ITeamRepository teams,
            ICompetitionRepository competitions)
        {
            _events = events;
            _contestants = contestants;
            _teams = teams;
            _competitions = competitions;
        }

        [BindProperty]
        public Contestant Contestant { get; set; }
        public List<SelectListItem> Teams { get; set; }
        public List<SelectListItem> Competitions { get; set; }

        public IActionResult OnGet(Guid eventId)
        {
            // authorize if logged in user is the owner of the event.
            var evenT = _events.GetFirstOrDefault(filter: p => p.EventId.Equals(eventId), p => p.ApplicationUser);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (evenT.ApplicationUserId != userId)
            {
                return RedirectToPage("/Event/Index", new { eventId = eventId });
            }

            Contestant = new Contestant()
            {
                EventId = eventId
            };

            PopulateSelectLists(eventId);

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                PopulateSelectLists(Contestant.EventId);
                return Page();
            }

            _contestants.Add(Contestant);
            _contestants.Save();

            return RedirectToPage("Index", new { eventId = Contestant.EventId });
        }

        public void PopulateSelectLists(Guid? eventId)
        {
            Teams = _teams
                .GetAll(
                    u => u.EventId.Equals(eventId),
                    include => include.Event)
                .Select(u => new SelectListItem
                {
                    Value = u.TeamId.ToString(),
                    Text = String.IsNullOrEmpty(u.Abbreviation) ? u.FullName : u.Abbreviation
                })
                .ToList();

            Competitions = _competitions
                .GetAll(
                    u => u.EventId.Equals(eventId),
                    include => include.Event)
                .Select(u => new SelectListItem
                {
                    Value = u.CompetitionId.ToString(),
                    Text = u.Name
                })
                .ToList();
        }
    }
}

Pages/Event/Add.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RandomDataGenerator.FieldOptions;
using RandomDataGenerator.Randomizers;
using System.Security.Claims;
using Utils;

namespace EventScoringWeb.Pages.Event
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class AddModel : PageModel
    {
        private readonly IEventRepository _events;

        public AddModel(IEventRepository events)
        {
            _events = events;
        }

        [BindProperty]
        public EventModel Event { get; set; }

        public void OnGet()
        {
            Event = new EventModel();
        }

        public async Task<IActionResult> OnPost()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return Page();
            }

            Event.ApplicationUserId = userId;
            if (Event.EventStartDate != null)
            {
                Event.EventStartDate = Convert.ToDateTime(
                    Event.EventStartDate.Value.ToShortDateString() + " " + DateTime.Now.ToShortTimeString() 
                );
            }
            if (Event.EventEndDate != null)
            {
                Event.EventEndDate = Convert.ToDateTime(
                    Event.EventEndDate.Value.ToShortDateString() + " " + DateTime.Now.ToShortTimeString()
                );
            }

            // Generate a random text (no numbers or special characters allowed)
            var randomizerText = RandomizerFactory.GetRandomizer(new FieldOptionsText { UseNumber = true, UseSpecial = false, Min = 10, Max = 10});
            string text = randomizerText.Generate()!;

            Event.Url = text;

            _events.Add(Event);
            _events.Save();

            return RedirectToPage("EventSingle", new { eventId = Event.EventId });
        }
    }
}

Pages/Judge/Index.cshtml.cs
using EventScoring.DataAccess.Repository.IRepository;
using EventScoring.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Utils;

namespace EventScoringWeb.Pages.Judge
{
    [Authorize(Roles = $"{AppRoles.EventHost},{AppRoles.Admin}")]
    public class IndexModel : PageModel
    {
        private readonly IApplicationUserRepository _users;
        private readonly IEventRepository _events;
        private readonly ICompetitionRepository _competitions;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public IndexModel(
            IApplicationUserRepository users, 
            IEventRepository events,
            ICompetitionRepository competitions,
            RoleManager<IdentityRole> roleManager, 
            UserManager<IdentityUser> userManager)
        {
            _users = users;
            _roleManager = roleManager;
            _userManager = userManager;
            _events = events;
            _competitions = competitions;
        }

        [BindProperty]
        public List<ApplicationUser> Judges { get; set; }

        public Guid EventId { get; set; }

        public IActionResult OnGet(Guid eventId)
        {
            // get id of logged in user
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            EventId = eventId;

            // get the associiated event 
            var evenT = _events.GetFirstOrDefault(u => u.EventId.Equals(eventId),
                includes: p => p.ApplicationUser);

            // do not allow access if logged in user is not the owner of the event
            if (evenT.ApplicationUserId != userId)
            {
                //return RedirectToPage("/AccessDenied");
                //return StatusCode(403);

                // To forbid user or just redirect back to /event/index?
                return Forbid();
            }


            var competitions = _competitions.GetAll(
                filter: p => p.EventId.Equals(eventId),
                p => p.Event, p => p.Judges);

            Judges = new List<ApplicationUser>();
            foreach (var competition in competitions)
            {
                foreach (var judge in competition.Judges)
                {
                    if (_userManager.IsInRoleAsync(judge, AppRoles.Judge).GetAwaiter().GetResult())
                    {
                        //Judges.AddRange(competition.Judges);
                        if (Judges.FirstOrDefault(u => u.Id == judge.Id) == null)
                        {
                            Judges.Add(judge);
                        }
                    }
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDelete(Guid eventId, string id)
        {
            var judge = (ApplicationUser)(await _userManager.FindByIdAsync(id));
            if (judge == null)
            {
                return NotFound($"Unable to load user with ID '{id}'");
            }

            try
            {
                _users.Remove(judge);
                _users.Save();
            }
            catch (Exception ex)
            {
                ViewData["delete-error"] = "An error occurred while attempting to delete user";
                return Page();
            }

            return RedirectToPage(nameof(Index), new { eventId });
        }
    }
}

ViewComponents/DashboardViewComponent.cs
using EventScoring.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace EventScoringWeb.ViewComponents
{
    public class DashboardViewComponent : ViewComponent
    {
        private readonly IEventRepository _events;
        public DashboardViewComponent(IEventRepository events)
        {
            _events = events;
        }

        public async Task<IViewComponentResult> InvokeAsync(DashboardViewModel viewModel)
        {
            viewModel.EventName = _events.GetFirstOrDefault(u => u.EventId.Equals(viewModel.EventId)).EventName;
            return View(viewModel);
        }
    }

    public class DashboardViewModel
    {
        public string Selected { get; set; }
        public Guid EventId { get; set; }
        public string EventName { get; set; }

        public string? Url { get; set; }
    }
}

Pages/Judge/Add.cshtml
@page
@using EventScoringWeb.ViewComponents
@model EventScoringWeb.Pages.Judge.AddModel
@{
    Layout = "_AuthenticatedLayout";

}

@await Component.InvokeAsync("Dashboard", new DashboardViewModel()
{
    EventId = (Guid)Model.Input.EventId,
    Selected = "judges",
})

<div id="page-content-wrapper">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-7">
                <div class="form-card">
                    <h1 class="h1 form-title">Add a Judge</h1>
                    <form method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input hidden asp-for="@Model.Input.EventId" />
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.FirstName"></label>
                            <input class="form-control" asp-for="@Model.Input.FirstName" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.LastName"></label>
                            <input class="form-control" asp-for="@Model.Input.LastName" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.Email"></label>
                            <input class="form-control" asp-for="@Model.Input.Email" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.Password"></label>
                            <input class="form-control" asp-for="@Model.Input.Password" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.ConfirmPassword"></label>
                            <input class="form-control" asp-for="@Model.Input.ConfirmPassword" />
                        </div>
                        @*         <div>
                        @Html.ListBoxFor(m => m.Input.CompetitionIds, Model.Competitions, "- Select Competition/s -")
                        </div> *@
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.CompetitionIds"></label>
                            <select class="multiselect multiselect-competitions form-select" asp-for="@Model.Input.CompetitionIds" multiple="multiple" asp-items="@Model.Competitions">

                            </select>
                            @* <select class="form-select" multiple asp-for="@Model.Input.CompetitionIds" asp-items="@Model.Competitions"></select> *@
                        </div>
                        <div class="text-end">
                            <button type="submit" class="btn btn-global">Add Judge</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.multiselect-competitions').select2();
        });
    </script>
}

Pages/Judge/Edit.cshtml
@page
@using EventScoringWeb.ViewComponents
@model EventScoringWeb.Pages.Judge.EditModel
@{
    Layout = "_AuthenticatedLayout";
}

@await Component.InvokeAsync("Dashboard", new DashboardViewModel()
{
    EventId = (Guid)Model.Input.EventId,
    Selected = "judges",
})

<div id="page-content-wrapper">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-7">
                <div class="form-card">
                    <h1 class="h1 form-title">Edit Judge</h1>
                    <form method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input hidden asp-for="@Model.Input.EventId" />
                        <input hidden asp-for="@Model.Input.Id"/>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.FirstName"></label>
                            <input class="form-control" asp-for="@Model.Input.FirstName" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.LastName"></label>
                            <input class="form-control" asp-for="@Model.Input.LastName" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.Email"></label>
                            <input class="form-control" asp-for="@Model.Input.Email" />
                        </div>
                        <div class="mb-3">
                            <label class="form-label text-secondary" asp-for="@Model.Input.SelectedCompetitions"></label>
                            <select class="multiselect multiselect-competitions form-select" asp-for="@Model.Input.SelectedCompetitions" multiple="multiple" asp-items="@Model.CompetitionList">
                            </select>
                        </div>
                        <div class="text-end">
                            <button type="submit" class="btn btn-global">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.multiselect-competitions').select2();
        });
    </script>
}

Pages/Judge/Home.cshtml
@page
@model EventScoringWeb.Pages.Judge.HomeModel

@using System.Security.Claims

@{
    Layout = "_NoDashboardLayout";
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}

<div id="page-content-wrapper">
    <div class="container">
        <div class="judge-home-header mb-5">
            <h1 class="h1 page-title mb-4">@Model.JudgeHomeVM.Event.EventName</h1>
            <p class="event-description text-secondary">
                Welcome judge! Below you will find the contestants that you need to score. Simply click on
                a contestant item below and it will take you to the scoring page.
            </p>
        </div>
        @foreach (var competition in Model.JudgeHomeVM.Competitions)
        {
            <div class="score-card mb-5">
                <div class="competition-title">
                    <h6 class="h6 m-0 py-2 ps-3">@competition.Name</h6>
                </div>

                <div class="list-container">
                    <div class="list-group contestant-list">
                        @foreach (var contestant in competition.Contestants)
                        {
                            <a 
                                class="list-group-item mb-3 p-3" 
                                asp-page="ScoreContestant" 
                                asp-route-competitionId="@competition.CompetitionId" 
                                asp-route-contestantId="@contestant.ContestantId">

                                <div class="row">
                                    <div class="col-12 col-md-7">
                                        <div class="d-flex flex-column justify-content-center ">
                                            <h5 class="team-name">@contestant.Team.FullName</h5>
                                            <h6 class="contestant-name">@contestant.FullName</h6>
                                        </div>
                                    </div>
                                    <div class="col-12 offset-md-2 col-md-3 text-end d-flex align-items-center justify-content-end">
                                        @{
                                            // Get all scores from contestant that the current has already scored
                                            var scores = contestant.Scores.Where(u => u.JudgeId == userId);

                                            // get total number of criteria for the competition
                                            var criteriaCount = competition.Criteria.Count();

                                            // if scores.Count() is not equal to criteriaCount,
                                            // judge user has not completed scoring
                                            if (scores.Count() != criteriaCount)
                                            {
                                                <div class="pending-status d-flex align-items-center gap-2">
                                                    <i class="bi bi-circle-fill align-middle"></i>
                                                    <div class="m-0">Pending</div>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="completed-status d-flex align-items-center gap-2">
                                                    <i class="bi bi-circle-fill align-middle"></i>
                                                    <div class="m-0">Completed</div>
                                                </div>
                                            }
                                        }
                                    </div>

                                </div>
                            </a>
                        }
                    </div>
                </div>
            </div>
        }

    </div>
</div>

Pages/Judge/Index.cshtml
@page
@using EventScoringWeb.ViewComponents
@model EventScoringWeb.Pages.Judge.IndexModel
@{
    Layout = "_AuthenticatedLayout";
}

@await Component.InvokeAsync("Dashboard", new DashboardViewModel()
{
    EventId = (Guid)Model.EventId,
    Selected = "judges",
})

<div id="page-content-wrapper">
    <div class="container">
        @if (ViewData.ContainsKey("delete-error"))
        {
            <p class="text-danger">
                @ViewData["delete-error"]
            </p>
        }
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1 class="h1 page-title">Judges</h1>
            <div>
                <a asp-page="Add" class="btn btn-global" asp-route-eventId="@Model.EventId">Add Judge</a>
            </div>
        </div>
@*         <div class="my-2">
            <a asp-page="Home" class="btn btn-link">Go to judge home</a>
        </div>
 *@
        <div>
            @if (Model.Judges.Count() == 0)
            {
                <div class="empty-page-container">
                    <h1 class="h1 empty-page-title">
                        It seems you currently do not have any judges added.
                    </h1>
                    <div>
                        <a asp-page="Add" class="btn btn-global" asp-route-eventId="@Model.EventId">Add Judge</a>
                    </div>
                </div>
            }
            else
            {
                <div class="table-responsive">
                    <table class="table table-dark entity-table">
                        <thead>
                            <tr>
                                <th>Full Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Competitions</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var judge in Model.Judges)
                            {
                                <tr>
                                    <td>@judge.FullName</td>
                                    <td>@judge.UserName</td>
                                    <td>@judge.Email</td>
                                    <td>
                                        @foreach (var competition in judge.Competitions)
                                        {
                                            <div class="p-1">@competition.Name</div>
                                        }
                                    </td>
                                    <td>
                                        <div class="m-1">
                                            <a class="btn text-white" asp-page="Edit" asp-route-eventId="@Model.EventId" asp-route-id="@judge.Id">
                                                <i class="bi bi-pencil-square"></i>
                                            </a>
                                            <form class="d-inline delete-form" method="POST" asp-page="Index" asp-page-handler="Delete" asp-route-id="@judge.Id" asp-route-eventId="@Model.EventId">
                                                <input asp-for="@Model.EventId" hidden />
                                                <button type="submit" class="btn text-white">
                                                    <i class="bi bi-trash"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>